import Link from "next/link";
import { ArrowRight, FileText, FolderKanban, Mail, TriangleAlert } from "lucide-react";
import { AdminPageTitle, AdminShell } from "@/components/admin/admin-shell";
import { requireAdmin } from "@/lib/auth";
import { getAdminOverview } from "@/lib/admin-data";
import { formatDate } from "@/lib/utils";

export const dynamic = "force-dynamic";

export default async function AdminDashboard() {
  const [session, overview] = await Promise.all([requireAdmin(), getAdminOverview()]);
  const cards = [["Projects", overview.projects, FolderKanban, "/admin/projects"], ["Blog posts", overview.posts, FileText, "/admin/posts"], ["New inquiries", overview.inquiries, Mail, "/admin/inquiries"]] as const;
  return <main><AdminShell email={session.email}><AdminPageTitle title="Dashboard" description="A compact view of your website content and client messages." />{!overview.configured ? <div className="mt-6 flex gap-3 rounded-2xl border border-amber-400/30 bg-amber-400/10 p-4 text-sm leading-6 text-amber-100"><TriangleAlert className="mt-0.5 size-5 shrink-0" /><p><strong>Database setup is incomplete.</strong> Add your MongoDB connection string to <code>.env.local</code> to activate the contact form, content management and dashboard data.</p></div> : null}<div className="mt-7 grid gap-4 md:grid-cols-3">{cards.map(([label, count, Icon, href]) => <Link href={href} key={label} className="group rounded-2xl border border-white/[.10] bg-[#0c0d12] p-5 transition hover:-translate-y-0.5 hover:shadow-lg"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-xl bg-[#12131a]"><Icon className="size-5" /></span><ArrowRight className="size-4 text-white/55 transition group-hover:translate-x-1" /></div><p className="mt-7 font-display text-4xl font-semibold tracking-[-.07em] text-white">{count}</p><p className="mt-1 text-sm font-semibold text-white/55">{label}</p></Link>)}</div><section className="mt-9"><h2 className="font-display text-xl font-semibold tracking-[-.04em] text-white">Latest inquiries</h2><div className="mt-4 overflow-x-auto rounded-2xl border border-white/[.10]"><table className="min-w-full text-left text-sm"><thead className="bg-ink/[.03] text-xs uppercase tracking-[.1em] text-white/55"><tr><th className="px-4 py-3 font-bold">Name</th><th className="px-4 py-3 font-bold">Service</th><th className="px-4 py-3 font-bold">Date</th></tr></thead><tbody>{overview.latest.length ? overview.latest.map((item) => <tr key={item._id} className="border-t border-white/[.08]"><td className="px-4 py-4"><p className="font-semibold text-white">{item.name}</p><p className="mt-1 text-xs text-white/55">{item.email}</p></td><td className="px-4 py-4 text-white/55">{item.service || "—"}</td><td className="px-4 py-4 text-white/55">{formatDate(item.createdAt)}</td></tr>) : <tr><td colSpan={3} className="px-4 py-8 text-center text-white/55">No inquiries yet.</td></tr>}</tbody></table></div></section></AdminShell></main>;
}
